#+title: Stefan's DOOM EMACS PACKAGES
#+author: Stefan Rohrbacher
#+startup: showeverything
#+property: header-args :tangle packages.el
#+auto_tangle: t
* INTRO :TOC:
  - [[#additional-info][ADDITIONAL INFO]]
- [[#header][Header]]
- [[#auto-tangle][Auto tangle]]
- [[#themes][Themes]]
- [[#dirvish][Dirvish]]
- [[#bpftrace][BPFTRACE]]
- [[#seq][seq]]
- [[#org-toc-disabled][ORG TOC (disabled)]]
- [[#toc-org][TOC ORG]]
- [[#beacon][BEACON]]
- [[#tldr-disabled][TLDR (disabled)]]
- [[#mpv-disabled][MPV (disabled)]]

** ADDITIONAL INFO
#+begin_src emacs-lisp :tangle no
(package! process)
          :recipe (:host github :repo "haji-ali/procress")
#+end_src

To install a package directly from a remote git repo, you must specify a
 `:recipe'. You'll find documentation on what `:recipe' accepts here:
 https://github.com/radian-software/straight.el#the-recipe-format

#+begin_src emacs-lisp :tangle no
(package! another-package
  :recipe (:host github :repo "username/repo"))
#+end_src

If the package you are trying to install does not contain a PACKAGENAME.el
file, or is located in a subdirectory of the repo, you'll need to specify
 `:files' in the `:recipe':
#+begin_src emacs-lisp :tangle no
(package! this-package
  :recipe (:host github :repo "username/repo"
           :files ("some-file.el" "src/lisp/*.el")))
#+end_src

If you'd like to disable a package included with Doom, you can do so here
with the `:disable' property:
#+begin_src emacs-lisp :tangle no
(package! builtin-package :disable t)
#+end_src

You can override the recipe of a built in package without having to specify
all the properties for `:recipe'. These will inherit the rest of its recipe
from Doom or MELPA/ELPA/Emacsmirror:
#+begin_src emacs-lisp :tangle no
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))
#+end_src

Specify a `:branch' to install a package from a particular branch or tag.
This is required for some packages whose default branch isn't 'master' (which
our package manager can't deal with; see radian-software/straight.el#279)

#+begin_src emacs-lisp :tangle no
(package! builtin-package :recipe (:branch "develop"))
#+end_src

Use `:pin' to specify a particular commit to install.
#+begin_src emacs-lisp :tangle no
(package! builtin-package :pin "1a2b3c4d5e")
#+end_src

Doom's packages are pinned to a specific commit and updated from release to
release. The `unpin!' macro allows you to unpin single packages...
#+begin_src emacs-lisp :tangle no
(unpin! pinned-package)
#+end_src

...or multiple packages
 #+begin_src emacs-lisp :tangle no
(unpin! pinned-package another-pinned-package)
#+end_src

...Or *all* packages (NOT RECOMMENDED; will likely break things)
#+begin_src emacs-lisp :tangle no
(unpin! t)
#+end_src


* Header
#+begin_src emacs-lisp
;;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+end_src

* Auto tangle
org babel auto tangle automatically tangles source code blocks on file save.
add ~#+auto_tangle: nil~ to disable or ~#+auto_tangle: t~ to enable this behavior.
#+begin_src emacs-lisp
(package! org-auto-tangle)
#+end_src

* Themes
#+begin_src emacs-lisp
(package! catppuccin-theme)
#+end_src

* Dirvish
#+begin_src emacs-lisp
(package! dirvish)
#+end_src

* BPFTRACE
#+begin_src emacs-lisp
(package! bpftrace-mode)
#+end_src

* seq
#+begin_src emacs-lisp
(package! seq)
#+end_src

* ORG TOC (disabled)
Generates a GitHub compatible TOC in org files.
Run: ~org-make-toc-insert~ to initialize the TOC and ~org-make-toc~ to refresh.
TOC must be the first thing after a heading, there can be no text before it!
#+begin_src emacs-lisp :tangle no
(package! org-make-toc)
#+end_src

* TOC ORG
Append ~:TOC:~ to a heading and a table of contents will be inserted/updated after the heading on every save.
#+begin_src emacs-lisp
(package! toc-org)
#+end_src

* BEACON
Adds a beacon to the cursor which flashes when focus or cursor position change.
#+begin_src emacs-lisp
(package! beacon)
#+end_src

* TLDR (disabled)
alternative to man-pages
#+begin_src emacs-lisp :tangle no
(package! tldr)
#+end_src

* MPV (disabled)
control mpv from emacs, can be done from emms
#+begin_src emacs-lisp :tangle no
(package! empv)
#+end_src
